# Generated by Django 4.0.2 on 2022-03-28 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_category', models.CharField(max_length=200, null=True)),
                ('number_of_bedrooms', models.IntegerField(null=True)),
                ('apartments_spaces', models.IntegerField(null=True)),
                ('apartments_available', models.IntegerField(null=True)),
                ('house_image', models.ImageField(null=True, upload_to='')),
                ('livingroom_image', models.ImageField(null=True, upload_to='')),
                ('kitchen_image', models.ImageField(null=True, upload_to='')),
                ('sanitaryroom_image', models.ImageField(null=True, upload_to='')),
                ('bathroom_image', models.ImageField(null=True, upload_to='')),
                ('bedroom', models.ImageField(null=True, upload_to='')),
                ('landlord', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
