# Generated by Django 4.0.2 on 2022-05-03 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing_operations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='bedroom',
            new_name='bedroom_image',
        ),
    ]
