# Generated by Django 4.0.2 on 2022-05-03 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housing_operations', '0003_remove_profile_address_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='house',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house', to='housing_operations.house'),
        ),
    ]
