# Generated by Django 4.0.2 on 2022-05-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_operations', '0004_profile_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
