# Generated by Django 4.0.2 on 2022-05-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_operations', '0005_house_house_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='apartments_available',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='apartments_spaces',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
