# Generated by Django 4.0.2 on 2022-05-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing_operations', '0006_alter_house_apartments_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='apartments_available',
        ),
        migrations.RemoveField(
            model_name='house',
            name='apartments_spaces',
        ),
        migrations.RemoveField(
            model_name='house',
            name='bathroom_image',
        ),
        migrations.RemoveField(
            model_name='house',
            name='bedroom_image',
        ),
        migrations.RemoveField(
            model_name='house',
            name='house_image',
        ),
        migrations.RemoveField(
            model_name='house',
            name='kitchen_image',
        ),
        migrations.RemoveField(
            model_name='house',
            name='livingroom_image',
        ),
        migrations.RemoveField(
            model_name='house',
            name='number_of_bedrooms',
        ),
        migrations.RemoveField(
            model_name='house',
            name='sanitaryroom_image',
        ),
    ]
