# Generated by Django 4.0.2 on 2022-05-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing_operations', '0007_remove_house_apartments_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='landlord',
        ),
    ]
